### ISSUE TITLE
uncurried2 is not a function

### ISSUE THREAD

**Issue by idkjs** [dmtrKovalenko/reason-date-fns#2]
Nice work here!

I was messing around with this and came upon this error;

```reason
        Js.Date.make()
        |> DateFns.addDays(1)
        |> DateFns.startOfDay
        |> DateFns.setHours(7.)
        |>Js.log2("test");
```

the error is:

```sh

/node_modules/reason-date-fns/src/ReasonDateFnsCurryHelpers.bs.js:6
  return uncurried2(a)(b);
         ^

TypeError: uncurried2 is not a function
```

Am i calling something incorrectly here?

Thanks and keep up the great work!

**Comment by dmtrKovalenko** [comment]
Hey! It looks like an issue with your setup. Here is codesandbox with working example https://codesandbox.io/s/gifted-water-t74z6
(I am not sure is it possible to make reasonml sandbox, but this is just copy of source files) everything works

**Comment by idkjs** [comment]
example say `.addDays is not a function`

<img width="1276" alt="Screenshot 2019-10-02 at 4 00 30 PM" src="https://user-images.githubusercontent.com/2370391/66077399-e16fcb80-e52d-11e9-8dfb-0af72bd6900b.png">

**Comment by dmtrKovalenko** [comment]
![image](https://user-images.githubusercontent.com/16926049/66077823-6e844600-e569-11e9-8924-eacb88be5e3a.png)

**Comment by idkjs** [comment]
That is super weird. I opened DateFns.bs.js and found this:

<img width="1276" alt="Screenshot 2019-10-02 at 4 31 44 PM" src="https://user-images.githubusercontent.com/2370391/66079543-43323480-e532-11e9-8229-bd2639254846.png">

**Comment by ohana54** [comment]
I'm also encountering similar errors, I think it's related to the fact that my project is using commonjs style requires, vs. es6 imports.

**Comment by kittipatv** [comment]
I ran into this and used https://github.com/SllyQ/bs-date-fns instead
